/**
 * This module contains action types.
 *
 * @format
 * @flow
 */

export const CHANGE_COMMENT_INPUT_VISIBILITY =
  "CHANGE_COMMENT_INPUT_VISIBILITY";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const FETCH_PRODUCT_COMMENTS_FAIL = "FETCH_PRODUCT_COMMENTS_FAIL";
export const FETCH_PRODUCT_COMMENTS_SUCCESS = "FETCH_PRODUCT_COMMENTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const OPEN_PRODUCT_INFO = "OPEN_PRODUCT_INFO";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const RESTORE_SESSION = "RESTORE_SESSION";

/*export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_FAIL";
export const FETCH_PRODUCT_COMMENTS_FAIL = "FETCH_PRODUCT_COMMENTS";
export const FETCH_PRODUCT_COMMENTS_SUCCESS = "FETCH_PRODUCT_COMMENTS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS";
export const POST_COMMENT_FAIL = "POST_COMMENT";
export const POST_COMMENT_SUCCESS = "POST_COMMENT";
export const REGISTER_FAIL = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER";*/
